FROM debian:latest

ENV UNAME=giliover

COPY entrypoint.chromium.sh /entrypoint.chromium.sh

RUN useradd giliover --password 12345678

RUN chmod +x /entrypoint.chromium.sh

RUN apt-get update

RUN apt-get install -y wget \
    qtbase5-dev \
    qtbase5-dev-tools \
    qtdeclarative5-dev \
    qttools5-dev \
    qttools5-dev-tools


RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

RUN chmod +x google-chrome-stable_current_amd64.deb

RUN apt-get install -f ./google-chrome-stable_current_amd64.deb

USER $UNAME

ENTRYPOINT ["/entrypoint.chromium.sh"]
