version: '3.8'

services:
  giliover-streamlink:
    container_name: giliover-streamlink
    image: giliover-streamlink
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    build:
      context: .
      dockerfile: ./Dockerfile.streamlink
    network_mode: "host"        
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd
    restart: always
  giliover-chromium:
    container_name: giliover-chromium
    image: giliover-chromium
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    build:
      context: .
      dockerfile: ./Dockerfile.chromium
    network_mode: "host"        
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd
    restart: no
  giliover-session:
    container_name: giliover-session
    image: giliover-session
    stdin_open: true
    privileged: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    build:
      context: .
      dockerfile: ./Dockerfile.session
    network_mode: "host"        
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd
    restart: always
  giliover-keepassxc:
    container_name: giliover-keepassxc
    image: giliover-keepassxc
    stdin_open: true
    privileged: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    build:
      context: .
      dockerfile: ./Dockerfile.keepassxc
    network_mode: "host"        
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./database.keepassxc:/home/ubuntu/config
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd
    restart: always
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
