FROM ubuntu:latest

ENV UNAME=ubuntu
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /home/ubuntu

RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://br.archive.ubuntu.com/ubuntu/|g' /etc/apt/sources.list /etc/apt/sources.list.d/ubuntu.sources


RUN apt-get update && apt-get install -y \
    streamlink \
    dbus-x11 \ 
    qtbase5-dev \
    qtbase5-dev-tools \
    qtdeclarative5-dev \
    qttools5-dev \
    qttools5-dev-tools

RUN apt-get install -y gnupg wget libfuse2 fuse libnss3

RUN wget https://github.com/streamlink/streamlink-twitch-gui/releases/download/v2.5.2/streamlink-twitch-gui-v2.5.2-x86_64.AppImage

RUN useradd giliover

RUN mv streamlink-twitch-gui-v2.5.2-x86_64.AppImage  streamlink.AppImage

COPY entrypoint.streamlink.sh entrypoint.streamlink.sh

RUN chmod +x streamlink.AppImage

RUN chmod +x entrypoint.streamlink.sh

RUN apt update && apt install -y wget bzip2

RUN wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" && \
    tar xjf firefox.tar.bz2 -C /opt/ && \
    ln -s /opt/firefox/firefox /usr/bin/firefox && \
    rm firefox.tar.bz2

RUN apt install -y curl

RUN mkdir -p /home/ubuntu/.local/share/streamlink/plugins
RUN curl -L -o "/home/ubuntu/.local/share/streamlink/plugins/twitch.py" 'https://github.com/2bc4/streamlink-ttvlol/releases/latest/download/twitch.py'

USER ubuntu

CMD ["./entrypoint.streamlink.sh"]
