FROM ubuntu:latest

ENV UNAME=ubuntu
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /home/ubuntu

RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://br.archive.ubuntu.com/ubuntu/|g' /etc/apt/sources.list /etc/apt/sources.list.d/ubuntu.sources

RUN apt-get update && apt-get install -y \
    wget \
    dbus-x11 \ 
    qtbase5-dev \
    qtbase5-dev-tools \
    qtdeclarative5-dev \
    qttools5-dev \
    qttools5-dev-tools

RUN wget https://github.com/VSCodium/vscodium/releases/download/1.94.2.24286/codium_1.94.2.24286_amd64.deb

RUN apt-get install -y ./codium_1.94.2.24286_amd64.deb

COPY entrypoint.codium.sh /entrypoint.codium.sh

RUN chmod +x /entrypoint.codium.sh

RUN apt-get install -y git

USER ubuntu

CMD ["/entrypoint.codium.sh"]
